name: Deployment CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    permissions:
      contents: write
      
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Node setup
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'npm'
    - run: npm ci
    - run: npm run build

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs
